language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -t cha0s92/multi-docker -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true cha0s92/multi-docker npm test

after_success:
 - docker build -t cha0s92/multi-client ./client
 - docker build -t cha0s92/multi-nginx ./nginx
 - docker build -t cha0s92/multi-server ./server
 - docker build -t cha0s92/multi-worker ./worker
 # login to Docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push image to docker hub
 - docker push cha0s92/multi-client
 - docker push cha0s92/multi-nginx
 - docker push cha0s92/multi-server
 - docker push cha0s92/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "Multidocker-env-1"
 bucket_name: "elasticbeanstalk-us-east-2-875738668938"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
